default_deploy_mode = "upload"

[build]
# options to allow building code against rust versions >=1.70 without opcodes
# incompatible with screeps server environments; requires nightly rust. See 
# https://github.com/rustyscreeps/screeps-game-api/issues/391
extra_options = ["--config", "build.rustflags=['-Ctarget-cpu=mvp']", "-Z", "build-std=std,panic_abort"]

[upload]
auth_token = "fa04ae5b-7def-4016-a063-ea641ab8e68e"
[upload.build]
  build-target="release"

[ptr]
auth_token = "your screeps.com auth token"
prefix = "ptr"

[copy]
# Windows Desktop
#destination = "C:\\Users\\jwjoh\\AppData\\Local\\Screeps\\scripts\\127_0_0_1___21025"
# Linux Laptop
#destination = "/home/jwjoh/.config/Screeps/scripts/127_0_0_1___21025"
# Bot arena
destination = "/home/jwjoh/.config/Screeps/scripts/botarena_screepspl_us___21025"

branch = "default"
[copy.build]
  # set the sim feature to allow for use with the coordinates in the simulation room
  #extra_options = ["--features=sim", "--config", "build.rustflags=['-Ctarget-cpu=mvp']", "-Z", "build-std=std,panic_abort"]
  extra_options = ["--features=sim"]
  #build-target = "release"

[season]
auth_token = "your screeps.com auth token"
prefix = "season"
  [season.build]
  extra_options = ["--features=my-crate-season-1-feature", "--config", "build.rustflags=['-Ctarget-cpu=mvp']", "-Z", "build-std=std,panic_abort", "-Z", "build-std-features=panic_immediate_abort"]

# for full syntax and available options, see
# https://github.com/rustyscreeps/screeps-game-api/blob/master/screeps-defaults.toml