name: Buildable?

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cargo-install
      uses: baptiste0928/cargo-install@v2.1.0
      with:
          crate: cargo-screeps
    - name: Build code
      run: cargo screeps build
          
